version: '3'

services: 
  database:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: teachinghub
    restart: always
    ports:
      - '3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    restart: always
    ports:
      - 8080:80